Python 3.7.0a4 (v3.7.0a4:07c9d85, Jan  9 2018, 06:16:56) [MSC v.1900 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
========== RESTART: C:\Users\DELL\Desktop\all_combination_hackr.py ==========
enter stringman
['man', 'mna', 'amn', 'anm', 'nam', 'nma']
['nam', 'anm', 'nma', 'mna', 'man', 'amn']
man
nam
anm
nma
mna
man
amn
mna
nam
anm
nma
mna
man
amn
amn
nam
anm
nma
mna
man
amn
anm
nam
anm
nma
mna
man
amn
nam
nam
anm
nma
mna
man
amn
nma
nam
anm
nma
mna
man
amn
36
anidrom
>>> 
========== RESTART: C:\Users\DELL\Desktop\all_combination_hackr.py ==========
enter string
========== RESTART: C:\Users\DELL\Desktop\all_combination_hackr.py ==========
enter stringPython 3.7.0a4 (v3.7.0a4:07c9d85, Jan  9 2018, 06:16:56) [MSC v.1900 32 bit (Intel)] on win32

========== RESTART: C:\Users\DELL\Desktop\all_combination_hackr.py ==========
enter stringman
['man', 'mna', 'amn', 'anm', 'nam', 'nma']
['nam', 'anm', 'nma', 'mna', 'man', 'amn']
man
mna
amn
anm
nam
nma
nam
anm
nma
mna
man
amn
6
anidrom
>>> 
========== RESTART: C:\Users\DELL\Desktop\all_combination_hackr.py ==========
enter stringman
['man', 'mna', 'amn', 'anm', 'nam', 'nma']
['nam', 'anm', 'nma', 'mna', 'man', 'amn']
man
mna
amn
anm
nam
nma
nam
anm
nma
mna
man
amn
1
anidrom
>>> 
========== RESTART: C:\Users\DELL\Desktop\all_combination_hackr.py ==========
enter stringman
['man', 'mna', 'amn', 'anm', 'nam', 'nma']
['nam', 'anm', 'nma', 'mna', 'man', 'amn']
man
Traceback (most recent call last):
  File "C:\Users\DELL\Desktop\all_combination_hackr.py", line 36, in <module>
    if (i==i.reverse):
AttributeError: 'str' object has no attribute 'reverse'
>>> 
>>> 
========== RESTART: C:\Users\DELL\Desktop\all_combination_hackr.py ==========
enter stringman
['man', 'mna', 'amn', 'anm', 'nam', 'nma']
['nam', 'anm', 'nma', 'mna', 'man', 'amn']
man
Traceback (most recent call last):
  File "C:\Users\DELL\Desktop\all_combination_hackr.py", line 36, in <module>
    if (i==i.reversed):
AttributeError: 'str' object has no attribute 'reversed'
>>> k='mam'
>>> 
========== RESTART: C:\Users\DELL\Desktop\all_combination_hackr.py ==========
enter stringman
['man', 'mna', 'amn', 'anm', 'nam', 'nma']
['nam', 'anm', 'nma', 'mna', 'man', 'amn']
man
mna
amn
anm
nam
nma
0
not anidrom
>>> 
========== RESTART: C:\Users\DELL\Desktop\all_combination_hackr.py ==========
enter stringmadam
['madam', 'madma', 'maadm', 'maamd', 'mamad', 'mamda', 'mdaam', 'mdama', 'mdmaa', 'mmdaa', 'mmada', 'mmaad', 'amdam', 'amdma', 'amadm', 'amamd', 'ammad', 'ammda', 'admam', 'admma', 'adamm', 'aadmm', 'aamdm', 'aammd', 'damam', 'damma', 'daamm', 'dmaam', 'dmama', 'dmmaa']
['madam', 'amdam', 'mdaam', 'dmaam', 'damam', 'admam', 'maadm', 'amadm', 'aamdm', 'aadmm', 'adamm', 'daamm', 'madma', 'amdma', 'mdama', 'dmama', 'damma', 'admma', 'mamda', 'ammda', 'mmada', 'mmdaa', 'mdmaa', 'dmmaa', 'mamad', 'ammad', 'mmaad', 'maamd', 'amamd', 'aammd']
madam
madma
maadm
maamd
mamad
mamda
mdaam
mdama
mdmaa
mmdaa
mmada
mmaad
amdam
amdma
amadm
amamd
ammad
ammda
admam
admma
adamm
aadmm
aamdm
aammd
damam
damma
daamm
dmaam
dmama
dmmaa
2
anidrom
>>> 
========== RESTART: C:\Users\DELL\Desktop\all_combination_hackr.py ==========
enter stringsolosolo
['solosolo', 'solosool', 'solosloo', 'solooslo', 'soloosol', 'soloolso', 'soloolos', 'soloools', 'solooosl', 'sololoso', 'sololoos', 'sololsoo', 'solsoolo', 'solsoool', 'solsoloo', 'solslooo', 'sollsooo', 'sollosoo', 'sollooso', 'sollooos', 'soolsolo', 'soolsool', 'soolsloo', 'sooloslo', 'soolosol', 'soololso', 'soololos', 'soolools', 'sooloosl', 'soolloso', 'soolloos', 'soollsoo', 'sooslolo', 'sooslool', 'sooslloo', 'soosollo', 'soosolol', 'soosooll', 'sooosllo', 'soooslol', 'sooosoll', 'sooolslo', 'sooolsol', 'sooollso', 'sooollos', 'sooolols', 'sooolosl', 'soooolls', 'soooolsl', 'soooosll', 'sosololo', 'sosolool', 'sosolloo', 'sosoollo', 'sosoolol', 'sosoooll', 'sosloolo', 'sosloool', 'sosloloo', 'sosllooo', 'sloosolo', 'sloosool', 'sloosloo', 'sloooslo', 'slooosol', 'slooolso', 'slooolos', 'slooools', 'sloooosl', 'slooloso', 'slooloos', 'sloolsoo', 'slosoolo', 'slosoool', 'slosoloo', 'sloslooo', 'slolsooo', 'slolosoo', 'slolooso', 'slolooos', 'slsooolo', 'slsooool', 'slsooloo', 'slsolooo', 'slsloooo', 'sllosooo', 'slloosoo', 'slloooso', 'slloooos', 'sllsoooo', 'sslooolo', 'sslooool', 'sslooloo', 'sslolooo', 'sslloooo', 'ssoloolo', 'ssoloool', 'ssololoo', 'ssollooo', 'ssoololo', 'ssoolool', 'ssoolloo', 'ssooollo', 'ssooolol', 'ssooooll', 'oslosolo', 'oslosool', 'oslosloo', 'oslooslo', 'osloosol', 'osloolso', 'osloolos', 'osloools', 'oslooosl', 'osloloso', 'osloloos', 'oslolsoo', 'oslsoolo', 'oslsoool', 'oslsoloo', 'oslslooo', 'osllsooo', 'osllosoo', 'osllooso', 'osllooos', 'osolsolo', 'osolsool', 'osolsloo', 'osoloslo', 'osolosol', 'osololso', 'osololos', 'osolools', 'osoloosl', 'osolloso', 'osolloos', 'osollsoo', 'ososlolo', 'ososlool', 'ososlloo', 'ososollo', 'ososolol', 'ososooll', 'osoosllo', 'osooslol', 'osoosoll', 'osoolslo', 'osoolsol', 'osoollso', 'osoollos', 'osoolols', 'osoolosl', 'osooolls', 'osooolsl', 'osooosll', 'ossololo', 'ossolool', 'ossolloo', 'ossoollo', 'ossoolol', 'ossoooll', 'ossloolo', 'ossloool', 'ossloloo', 'ossllooo', 'olsosolo', 'olsosool', 'olsosloo', 'olsooslo', 'olsoosol', 'olsoolso', 'olsoolos', 'olsoools', 'olsooosl', 'olsoloso', 'olsoloos', 'olsolsoo', 'olssoolo', 'olssoool', 'olssoloo', 'olsslooo', 'olslsooo', 'olslosoo', 'olslooso', 'olslooos', 'olossolo', 'olossool', 'olossloo', 'olososlo', 'olososol', 'olosolso', 'olosolos', 'olosools', 'olosoosl', 'olosloso', 'olosloos', 'oloslsoo', 'oloosslo', 'oloossol', 'olooslso', 'olooslos', 'oloosols', 'oloososl', 'oloolsso', 'oloolsos', 'olooloss', 'olooosls', 'olooossl', 'olooolss', 'ololsoso', 'ololsoos', 'ololssoo', 'ololosso', 'ololosos', 'ololooss', 'ollososo', 'ollosoos', 'ollossoo', 'olloosso', 'olloosos', 'olloooss', 'ollsooso', 'ollsooos', 'ollsosoo', 'ollssooo', 'oolssolo', 'oolssool', 'oolssloo', 'oolsoslo', 'oolsosol', 'oolsolso', 'oolsolos', 'oolsools', 'oolsoosl', 'oolsloso', 'oolsloos', 'oolslsoo', 'oolosslo', 'oolossol', 'ooloslso', 'ooloslos', 'oolosols', 'oolososl', 'oololsso', 'oololsos', 'oololoss', 'ooloosls', 'ooloossl', 'ooloolss', 'oollsoso', 'oollsoos', 'oollssoo', 'oollosso', 'oollosos', 'oollooss', 'ooslsolo', 'ooslsool', 'ooslsloo', 'oosloslo', 'ooslosol', 'ooslolso', 'ooslolos', 'ooslools', 'oosloosl', 'ooslloso', 'ooslloos', 'oosllsoo', 'oosslolo', 'oosslool', 'oosslloo', 'oossollo', 'oossolol', 'oossooll', 'oososllo', 'oososlol', 'oososoll', 'oosolslo', 'oosolsol', 'oosollso', 'oosollos', 'oosolols', 'oosolosl', 'oosoolls', 'oosoolsl', 'oosoosll', 'ooossllo', 'ooosslol', 'ooossoll', 'oooslslo', 'oooslsol', 'ooosllso', 'ooosllos', 'oooslols', 'oooslosl', 'ooosolls', 'ooosolsl', 'ooososll', 'ooolsslo', 'ooolssol', 'ooolslso', 'ooolslos', 'ooolsols', 'ooolsosl', 'ooollsso', 'ooollsos', 'ooolloss', 'ooolosls', 'ooolossl', 'ooololss', 'ooooslls', 'ooooslsl', 'oooossll', 'oooolsls', 'oooolssl', 'oooollss', 'lososolo', 'lososool', 'lososloo', 'losooslo', 'losoosol', 'losoolso', 'losoolos', 'losoools', 'losooosl', 'losoloso', 'losoloos', 'losolsoo', 'lossoolo', 'lossoool', 'lossoloo', 'losslooo', 'loslsooo', 'loslosoo', 'loslooso', 'loslooos', 'loossolo', 'loossool', 'loossloo', 'loososlo', 'loososol', 'loosolso', 'loosolos', 'loosools', 'loosoosl', 'loosloso', 'loosloos', 'looslsoo', 'looosslo', 'looossol', 'loooslso', 'loooslos', 'looosols', 'looososl', 'looolsso', 'looolsos', 'loooloss', 'loooosls', 'loooossl', 'loooolss', 'loolsoso', 'loolsoos', 'loolssoo', 'loolosso', 'loolosos', 'loolooss', 'lolososo', 'lolosoos', 'lolossoo', 'loloosso', 'loloosos', 'loloooss', 'lolsooso', 'lolsooos', 'lolsosoo', 'lolssooo', 'lsoosolo', 'lsoosool', 'lsoosloo', 'lsoooslo', 'lsooosol', 'lsooolso', 'lsooolos', 'lsooools', 'lsoooosl', 'lsooloso', 'lsooloos', 'lsoolsoo', 'lsosoolo', 'lsosoool', 'lsosoloo', 'lsoslooo', 'lsolsooo', 'lsolosoo', 'lsolooso', 'lsolooos', 'lssooolo', 'lssooool', 'lssooloo', 'lssolooo', 'lssloooo', 'lslosooo', 'lsloosoo', 'lsloooso', 'lsloooos', 'lslsoooo', 'llsosooo', 'llsoosoo', 'llsoooso', 'llsoooos', 'llssoooo', 'llossooo', 'llososoo', 'llosooso', 'llosooos', 'lloossoo', 'lloososo', 'lloosoos', 'llooosso', 'llooosos', 'llooooss']
['olosolos', 'loosolos', 'oolsolos', 'olsoolos', 'losoolos', 'osloolos', 'soloolos', 'slooolos', 'lsooolos', 'osololos', 'soololos', 'ooslolos', 'olooslos', 'loooslos', 'ooloslos', 'ooolslos', 'ooosllos', 'oosollos', 'osoollos', 'sooollos', 'olosloos', 'loosloos', 'oolsloos', 'olsoloos', 'losoloos', 'osloloos', 'sololoos', 'slooloos', 'lsooloos', 'osolloos', 'soolloos', 'ooslloos', 'ololsoos', 'loolsoos', 'oollsoos', 'ollosoos', 'lolosoos', 'lloosoos', 'ollsooos', 'lolsooos', 'llosooos', 'olslooos', 'loslooos', 'osllooos', 'sollooos', 'slolooos', 'lsolooos', 'slloooos', 'lsloooos', 'llsoooos', 'ololosos', 'loolosos', 'oollosos', 'olloosos', 'loloosos', 'llooosos', 'oloolsos', 'looolsos', 'oololsos', 'ooollsos', 'olosools', 'loosools', 'oolsools', 'olsoools', 'losoools', 'osloools', 'soloools', 'slooools', 'lsooools', 'osolools', 'soolools', 'ooslools', 'oloosols', 'looosols', 'oolosols', 'ooolsols', 'oooslols', 'oosolols', 'osoolols', 'sooolols', 'olooosls', 'loooosls', 'ooloosls', 'ooolosls', 'oooolsls', 'ooosolls', 'oosoolls', 'osooolls', 'soooolls', 'ooooslls', 'olooolss', 'loooolss', 'ooloolss', 'ooololss', 'oooollss', 'olooloss', 'loooloss', 'oololoss', 'ooolloss', 'ololooss', 'loolooss', 'oollooss', 'olloooss', 'loloooss', 'llooooss', 'olosolso', 'loosolso', 'oolsolso', 'olsoolso', 'losoolso', 'osloolso', 'soloolso', 'slooolso', 'lsooolso', 'osololso', 'soololso', 'ooslolso', 'olooslso', 'loooslso', 'ooloslso', 'ooolslso', 'ooosllso', 'oosollso', 'osoollso', 'sooollso', 'olosloso', 'loosloso', 'oolsloso', 'olsoloso', 'losoloso', 'osloloso', 'sololoso', 'slooloso', 'lsooloso', 'osolloso', 'soolloso', 'ooslloso', 'ololsoso', 'loolsoso', 'oollsoso', 'ollososo', 'lolososo', 'lloososo', 'ollsooso', 'lolsooso', 'llosooso', 'olslooso', 'loslooso', 'osllooso', 'sollooso', 'slolooso', 'lsolooso', 'slloooso', 'lsloooso', 'llsoooso', 'ololosso', 'loolosso', 'oollosso', 'olloosso', 'loloosso', 'llooosso', 'oloolsso', 'looolsso', 'oololsso', 'ooollsso', 'olososlo', 'loososlo', 'oolsoslo', 'olsooslo', 'losooslo', 'oslooslo', 'solooslo', 'sloooslo', 'lsoooslo', 'osoloslo', 'sooloslo', 'oosloslo', 'oloosslo', 'looosslo', 'oolosslo', 'ooolsslo', 'oooslslo', 'oosolslo', 'osoolslo', 'sooolslo', 'olossolo', 'loossolo', 'oolssolo', 'olsosolo', 'lososolo', 'oslosolo', 'solosolo', 'sloosolo', 'lsoosolo', 'osolsolo', 'soolsolo', 'ooslsolo', 'olssoolo', 'lossoolo', 'oslsoolo', 'solsoolo', 'slosoolo', 'lsosoolo', 'ossloolo', 'sosloolo', 'ssoloolo', 'slsooolo', 'lssooolo', 'sslooolo', 'ososlolo', 'sooslolo', 'oosslolo', 'ossololo', 'sosololo', 'ssoololo', 'ososollo', 'soosollo', 'oossollo', 'ossoollo', 'sosoollo', 'ssooollo', 'osoosllo', 'sooosllo', 'oososllo', 'ooossllo', 'olossloo', 'loossloo', 'oolssloo', 'olsosloo', 'lososloo', 'oslosloo', 'solosloo', 'sloosloo', 'lsoosloo', 'osolsloo', 'soolsloo', 'ooslsloo', 'olssoloo', 'lossoloo', 'oslsoloo', 'solsoloo', 'slosoloo', 'lsosoloo', 'ossloloo', 'sosloloo', 'ssololoo', 'slsooloo', 'lssooloo', 'sslooloo', 'ososlloo', 'sooslloo', 'oosslloo', 'ossolloo', 'sosolloo', 'ssoolloo', 'oloslsoo', 'looslsoo', 'oolslsoo', 'olsolsoo', 'losolsoo', 'oslolsoo', 'sololsoo', 'sloolsoo', 'lsoolsoo', 'osollsoo', 'soollsoo', 'oosllsoo', 'ololssoo', 'loolssoo', 'oollssoo', 'ollossoo', 'lolossoo', 'lloossoo', 'ollsosoo', 'lolsosoo', 'llososoo', 'olslosoo', 'loslosoo', 'osllosoo', 'sollosoo', 'slolosoo', 'lsolosoo', 'slloosoo', 'lsloosoo', 'llsoosoo', 'ollssooo', 'lolssooo', 'llossooo', 'olslsooo', 'loslsooo', 'osllsooo', 'sollsooo', 'slolsooo', 'lsolsooo', 'sllosooo', 'lslosooo', 'llsosooo', 'olsslooo', 'losslooo', 'oslslooo', 'solslooo', 'sloslooo', 'lsoslooo', 'ossllooo', 'sosllooo', 'ssollooo', 'slsolooo', 'lssolooo', 'sslolooo', 'sllsoooo', 'lslsoooo', 'llssoooo', 'slsloooo', 'lssloooo', 'sslloooo', 'olososol', 'loososol', 'oolsosol', 'olsoosol', 'losoosol', 'osloosol', 'soloosol', 'slooosol', 'lsooosol', 'osolosol', 'soolosol', 'ooslosol', 'oloossol', 'looossol', 'oolossol', 'ooolssol', 'oooslsol', 'oosolsol', 'osoolsol', 'sooolsol', 'olossool', 'loossool', 'oolssool', 'olsosool', 'lososool', 'oslosool', 'solosool', 'sloosool', 'lsoosool', 'osolsool', 'soolsool', 'ooslsool', 'olssoool', 'lossoool', 'oslsoool', 'solsoool', 'slosoool', 'lsosoool', 'ossloool', 'sosloool', 'ssoloool', 'slsooool', 'lssooool', 'sslooool', 'ososlool', 'sooslool', 'oosslool', 'ossolool', 'sosolool', 'ssoolool', 'ososolol', 'soosolol', 'oossolol', 'ossoolol', 'sosoolol', 'ssooolol', 'osooslol', 'soooslol', 'oososlol', 'ooosslol', 'olosoosl', 'loosoosl', 'oolsoosl', 'olsooosl', 'losooosl', 'oslooosl', 'solooosl', 'sloooosl', 'lsoooosl', 'osoloosl', 'sooloosl', 'oosloosl', 'oloososl', 'looososl', 'oolososl', 'ooolsosl', 'oooslosl', 'oosolosl', 'osoolosl', 'sooolosl', 'olooossl', 'loooossl', 'ooloossl', 'ooolossl', 'oooolssl', 'ooosolsl', 'oosoolsl', 'osooolsl', 'soooolsl', 'ooooslsl', 'ooososll', 'oosoosll', 'osooosll', 'soooosll', 'oooossll', 'ooossoll', 'oososoll', 'osoosoll', 'sooosoll', 'oossooll', 'ososooll', 'soosooll', 'ossoooll', 'sosoooll', 'ssooooll']
solosolo
solosool
solosloo
solooslo
soloosol
soloolso
soloolos
soloools
solooosl
sololoso
sololoos
sololsoo
solsoolo
solsoool
solsoloo
solslooo
sollsooo
sollosoo
sollooso
sollooos
soolsolo
soolsool
soolsloo
sooloslo
soolosol
soololso
soololos
soolools
sooloosl
soolloso
soolloos
soollsoo
sooslolo
sooslool
sooslloo
soosollo
soosolol
soosooll
sooosllo
soooslol
sooosoll
sooolslo
sooolsol
sooollso
sooollos
sooolols
sooolosl
soooolls
soooolsl
soooosll
sosololo
sosolool
sosolloo
sosoollo
sosoolol
sosoooll
sosloolo
sosloool
sosloloo
sosllooo
sloosolo
sloosool
sloosloo
sloooslo
slooosol
slooolso
slooolos
slooools
sloooosl
slooloso
slooloos
sloolsoo
slosoolo
slosoool
slosoloo
sloslooo
slolsooo
slolosoo
slolooso
slolooos
slsooolo
slsooool
slsooloo
slsolooo
slsloooo
sllosooo
slloosoo
slloooso
slloooos
sllsoooo
sslooolo
sslooool
sslooloo
sslolooo
sslloooo
ssoloolo
ssoloool
ssololoo
ssollooo
ssoololo
ssoolool
ssoolloo
ssooollo
ssooolol
ssooooll
oslosolo
oslosool
oslosloo
oslooslo
osloosol
osloolso
osloolos
osloools
oslooosl
osloloso
osloloos
oslolsoo
oslsoolo
oslsoool
oslsoloo
oslslooo
osllsooo
osllosoo
osllooso
osllooos
osolsolo
osolsool
osolsloo
osoloslo
osolosol
osololso
osololos
osolools
osoloosl
osolloso
osolloos
osollsoo
ososlolo
ososlool
ososlloo
ososollo
ososolol
ososooll
osoosllo
osooslol
osoosoll
osoolslo
osoolsol
osoollso
osoollos
osoolols
osoolosl
osooolls
osooolsl
osooosll
ossololo
ossolool
ossolloo
ossoollo
ossoolol
ossoooll
ossloolo
ossloool
ossloloo
ossllooo
olsosolo
olsosool
olsosloo
olsooslo
olsoosol
olsoolso
olsoolos
olsoools
olsooosl
olsoloso
olsoloos
olsolsoo
olssoolo
olssoool
olssoloo
olsslooo
olslsooo
olslosoo
olslooso
olslooos
olossolo
olossool
olossloo
olososlo
olososol
olosolso
olosolos
olosools
olosoosl
olosloso
olosloos
oloslsoo
oloosslo
oloossol
olooslso
olooslos
oloosols
oloososl
oloolsso
oloolsos
olooloss
olooosls
olooossl
olooolss
ololsoso
ololsoos
ololssoo
ololosso
ololosos
ololooss
ollososo
ollosoos
ollossoo
olloosso
olloosos
olloooss
ollsooso
ollsooos
ollsosoo
ollssooo
oolssolo
oolssool
oolssloo
oolsoslo
oolsosol
oolsolso
oolsolos
oolsools
oolsoosl
oolsloso
oolsloos
oolslsoo
oolosslo
oolossol
ooloslso
ooloslos
oolosols
oolososl
oololsso
oololsos
oololoss
ooloosls
ooloossl
ooloolss
oollsoso
oollsoos
oollssoo
oollosso
oollosos
oollooss
ooslsolo
ooslsool
ooslsloo
oosloslo
ooslosol
ooslolso
ooslolos
ooslools
oosloosl
ooslloso
ooslloos
oosllsoo
oosslolo
oosslool
oosslloo
oossollo
oossolol
oossooll
oososllo
oososlol
oososoll
oosolslo
oosolsol
oosollso
oosollos
oosolols
oosolosl
oosoolls
oosoolsl
oosoosll
ooossllo
ooosslol
ooossoll
oooslslo
oooslsol
ooosllso
ooosllos
oooslols
oooslosl
ooosolls
ooosolsl
ooososll
ooolsslo
ooolssol
ooolslso
ooolslos
ooolsols
ooolsosl
ooollsso
ooollsos
ooolloss
ooolosls
ooolossl
ooololss
ooooslls
ooooslsl
oooossll
oooolsls
oooolssl
oooollss
lososolo
lososool
lososloo
losooslo
losoosol
losoolso
losoolos
losoools
losooosl
losoloso
losoloos
losolsoo
lossoolo
lossoool
lossoloo
losslooo
loslsooo
loslosoo
loslooso
loslooos
loossolo
loossool
loossloo
loososlo
loososol
loosolso
loosolos
loosools
loosoosl
loosloso
loosloos
looslsoo
looosslo
looossol
loooslso
loooslos
looosols
looososl
looolsso
looolsos
loooloss
loooosls
loooossl
loooolss
loolsoso
loolsoos
loolssoo
loolosso
loolosos
loolooss
lolososo
lolosoos
lolossoo
loloosso
loloosos
loloooss
lolsooso
lolsooos
lolsosoo
lolssooo
lsoosolo
lsoosool
lsoosloo
lsoooslo
lsooosol
lsooolso
lsooolos
lsooools
lsoooosl
lsooloso
lsooloos
lsoolsoo
lsosoolo
lsosoool
lsosoloo
lsoslooo
lsolsooo
lsolosoo
lsolooso
lsolooos
lssooolo
lssooool
lssooloo
lssolooo
lssloooo
lslosooo
lsloosoo
lsloooso
lsloooos
lslsoooo
llsosooo
llsoosoo
llsoooso
llsoooos
llssoooo
llossooo
llososoo
llosooso
llosooos
lloossoo
lloososo
lloosoos
llooosso
llooosos
llooooss
12
anidrom
>>> 
=================== RESTART: F:/python program/anidrome.py ===================
enter string
